# Generated by Django 5.0.4 on 2024-11-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stagiairesencours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField()),
                ('findustage', models.DateField()),
                ('qualite', models.TextField()),
                ('stage', models.TextField()),
                ('debutdustage', models.DateField()),
                ('division', models.TextField()),
                ('encadrent', models.TextField()),
            ],
        ),
    ]
