# Generated by Django 5.0.4 on 2024-11-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiairesencours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiairesencours',
            name='etablissement',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
