# Generated by Django 5.0.4 on 2024-10-11 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stagiaires', '0002_alter_stagiaire_findustage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.IntegerField()),
                ('nom', models.CharField(default='Inconnu', max_length=100)),
                ('prenom', models.CharField(default='Inconnu', max_length=100)),
                ('justification', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('stagiaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stagiaires.stagiaire')),
            ],
        ),
    ]
