# Generated by Django 5.0.4 on 2024-10-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='stagiaire',
        ),
        migrations.AlterField(
            model_name='absence',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='absence',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
