# Generated by Django 5.0.4 on 2024-10-13 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_remove_absence_stagiaire_alter_absence_nom_and_more'),
        ('stagiaires', '0002_alter_stagiaire_findustage'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='stagiaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stagiaires.stagiaire'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='nom',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AlterField(
            model_name='absence',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
    ]
