# Generated by Django 5.0.4 on 2024-10-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0003_absence_stagiaire_alter_absence_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='absence',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
