# Generated by Django 5.0.4 on 2024-11-26 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0004_alter_absence_nom_alter_absence_prenom'),
        ('stagiairesencours', '0002_stagiairesencours_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='stagiaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stagiairesencours.stagiairesencours'),
        ),
    ]
