# Generated by Django 5.0.4 on 2024-09-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='findustage',
            field=models.DateField(),
        ),
    ]
